logger:
  output: text
  debug: false

bitcoin_node:
  host: "bitcoin-mainnet-archive.allthatnode.com"
  user: "user"
  pass: "pass"
  disable_tls: false

network: mainnet

modules:
  bitcoin:
    database: "postgres" # Database to store bitcoin data. current supported databases: "postgres"
    postgres:
      host: "localhost"
      port: 5432
      user: "postgres"
      password: "password"
      db_name: "postgres"
      # url: "postgres://postgres:password@localhost:5432/postgres?sslmode=prefer" # [Optional] This will override other database connection configurations
  runes:
    database: "postgres" # Database to store Runes data. current supported databases: "postgres"
    datasource: "bitcoin-node"
    postgres:
      host: "localhost"
      port: 5432
      user: "postgres"
      password: "password"
      db_name: "postgres"
      # url: "postgres://postgres:password@localhost:5432/postgres?sslmode=prefer" # [Optional] This will override other database connection configurations
