logger:
  output: text
  debug: false

bitcoin_node:
  host: "bitcoin-mainnet-archive.allthatnode.com"
  user: "user"
  pass: "pass"
  disable_tls: false

network: mainnet

reporting:
  disabled: false
  base_url: "https://indexer.api.gaze.network" # defaults to "https://indexer.api.gaze.network" if empty
  name: "local-dev" # name of this instance to show on the dashboard
  website_url: "" # public website URL to show on the dashboard. Can be left empty.
  indexer_api_url: "" # public url to access this api. Can be left empty.

้http_server:
  port: 8080

modules:
  bitcoin:
    database: "postgres" # Database to store bitcoin data. current supported databases: "postgres"
    postgres:
      host: "localhost"
      port: 5432
      user: "postgres"
      password: "password"
      db_name: "postgres"
      # url: "postgres://postgres:password@localhost:5432/postgres?sslmode=prefer" # [Optional] This will override other database connection configurations
  runes:
    database: "postgres" # Database to store Runes data. current supported databases: "postgres"
    datasource: "postgres" # Data source to be used (to fetch bitcoin blocks). current supported data sources: "bitcoin-node" | "postgres"
    api_handlers: # API handlers to be used. current supported handlers: "http"
      - http
    postgres:
      host: "localhost"
      port: 5432
      user: "postgres"
      password: "password"
      db_name: "postgres"
      # url: "postgres://postgres:password@localhost:5432/postgres?sslmode=prefer" # [Optional] This will override other database connection configurations
