logger:
  output: text
  debug: false

bitcoin_node:
  host: "bitcoin-mainnet-archive.allthatnode.com"
  user: "user"
  pass: "pass"
  disable_tls: false

modules:
  bitcoin:
    postgresql:
      host: "localhost"
      port: 5432
      user: "postgres"
      pass: "password"
      db: "postgres"
      # url: "postgres://postgres:password@localhost:5432/postgres?sslmode=prefer" # [Optional] This will override other database connection configurations
