name: Sqlc ORM Framework Verify
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "sqlc.yaml"
      - "**.sql"
      - ".github/workflows/sqlc-verify.yml"

jobs:
  sqlc-diff:
    name: Sqlc Diff Checker
    runs-on: "ubuntu-latest" # "self-hosted", "ubuntu-latest", "macos-latest", "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Setup Sqlc
        uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: "1.27.0"

      - name: Check Diff
        run: sqlc diff
